global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "go-service"
    static_configs:
      - targets: ["go-service:8080"]
    metrics_path: /metrics

  - job_name: "node-service"
    static_configs:
      - targets: ["node-service:8080"]
    metrics_path: /metrics

  - job_name: "python-service"
    static_configs:
      - targets: ["python-service:8080"]
    metrics_path: /metrics
