# TODO: Write Dockerfile for Python service

FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
# RUN pip install -r requirements.txt
COPY . .

CMD ["echo", "Write your Dockerfile instructions"]
